resolver: lts-12.2

packages:
  - location: .
  - location:
      git: https://github.com/idris-lang/Idris-dev.git
      commit: master
    extra-dep: true
flags:
  idris:
    FFI: false
    GMP: true

nix:
  enable: false
  shell-file: stack-shell.nix
