resolver: lts-12.2

packages:
  - location: .
  - location:
      git: https://github.com/idris-lang/Idris-dev.git
      commit: master
    extra-dep: true
flags:
  idris:
    FFI: true
    GMP: true

extra-deps:
  - libffi-0.1
  
nix:
  enable: false
  shell-file: stack-shell.nix
